# TODO 配置数据源相关信息

server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&useServerPrepStmts=true&characterEncoding=utf8
    username: root
    password: 123456
# 配置 mybatis domain 包
mybatis:
  type-aliases-package: com.geekaca.news.newssys.domain